# Site settings
email: lin.zhang.cs@gmail.com
baseurl:
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Lin's Portfolio
description: Lin Zhang's (SLC, UT) website. Lin's past projects
url: "https://linzhangcs.github.io/hi"
twitter_username:
default_img:

# Profile settings
name: Lin Zhang
profile_img: http://linzhangcs.github.io/img/selfielins.jpg
profile: Lin likes the Internet so she became a developer. Thanks for taking a look at her portfolio.
social:
  github: http://github.com/linzhangcs
  linkedin: https://www.linkedin.com/in/lin-zhang-7453b639
  # facebook: https://www.facebook.com/lin.zhang.796
  instagram: https://www.instagram.com/heartsmiles

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
